---
- name: Common setup for all machines
  hosts: web
  become: true
  tasks:
    - name: Stop and disable firewalld
      ansible.builtin.systemd:
        name: firewalld
        state: stopped
        enabled: false

    - name: Set timezone to Europe/Bucharest
      community.general.timezone:
        name: Europe/Bucharest

    - name: Set PermitRootLogin to prohibit-password
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?PermitRootLogin\s+.*'
        line: "PermitRootLogin prohibit-password"
        state: present
      notify: Restart SSH

    - name: Add Docker repository
      ansible.builtin.yum_repository:
        name: docker-ce-stable
        description: Docker CE Stable
        baseurl: https://download.docker.com/linux/centos/$releasever/$basearch/stable
        gpgcheck: true
        gpgkey: https://download.docker.com/linux/centos/gpg
        enabled: true

    - name: Install Docker
      ansible.builtin.package:
        name: "{{ item }}"
        state: present
      with_items:
        - docker-ce
        - docker-ce-cli
        - containerd.io
        - docker-compose-plugin

    - name: Start and enable Docker service
      ansible.builtin.service:
        name: docker
        state: started
        enabled: true


    - name: Copy Root CA to trust store
      ansible.builtin.copy:
        src: easy-rsa/pki/ca.crt
        dest: /etc/pki/ca-trust/source/anchors/mihai-root-ca.crt
        owner: root
        group: root
        mode: '0644'
      notify: Update CA Trust

    - name: Disable SELinux
      ansible.posix.selinux:
        state: disabled

  handlers:
    - name: Restart SSH
      ansible.builtin.service:
        name: sshd
        state: restarted

    - name: Update CA Trust
      ansible.builtin.command: update-ca-trust
